SIMPLES/core/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, reverse, include


urlpatterns = [
    path("secret-admin/", admin.site.urls),
    path("", include("myapp.urls")),
    path('pix/', include('pix.urls')),
   



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SIMPLES/pix/urls.py
from django.urls import path
from . import views

app_name = 'pix'

urlpatterns = [
    path('gerar-pix/', views.processar_cobranca_pix, name='gerar_pix'),
    path('sucesso/<str:id_loc>/', views.sucesso, name='sucesso'),
]   

SIMPLES/pix/models.py
from django.db import models

class Pagamento(models.Model):
    STATUS_CHOICES = [
        ('pendente', 'Pendente'),
        ('pago', 'Pago'),
        ('cancelado', 'Cancelado'),
    ]

    # Informações do devedor
    cpf = models.CharField(max_length=11, verbose_name="CPF do Devedor")
    nome = models.CharField(max_length=255, verbose_name="Nome do Devedor")

    # Informações sobre o pagamento
    valor = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Valor da Cobrança")

    # Dados do Pix
    txid = models.CharField(max_length=255, null=True, blank=True, verbose_name="Txid do Pagamento")
    id_loc = models.CharField(max_length=255, null=True, blank=True, verbose_name="ID da Localização")
    qr_code = models.TextField(max_length=255, null=True, blank=True, verbose_name="QR Code")
    link_visualizacao = models.URLField(null=True, blank=True, verbose_name="Link de Visualização")
    imagem_qrcode = models.TextField(null=True, blank=True, verbose_name="Imagem do QR Code")
    email = models.EmailField(default='ongamigo@esperanca')
    mensagem = models.TextField(blank=True, null=True)
    
    # Status do pagamento
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pendente', verbose_name="Status do Pagamento")
    
    # Campos para rastreamento (como data de criação e última atualização)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Última Atualização")

    def __str__(self):
        return f"Pagamento {self.id} - {self.nome} - {self.valor}"

    class Meta:
        verbose_name = "Pagamento"
        verbose_name_plural = "Pagamentos"
        ordering = ['-created_at']

SIMPLES/pix/forms.py
# pix/forms.py

from django import forms
from .models import Pagamento
from django.forms.widgets import NumberInput

class PagamentoForm(forms.ModelForm):
    class Meta:
        model = Pagamento
        fields = ['nome', 'cpf', 'email', 'valor', 'mensagem']

    valor = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        widget=NumberInput(attrs={'step': '0.01'})
    )

SIMPLES/pix/views.py
import os
import base64
import requests
from .models import Pagamento
from django.http import Http404
from .forms import PagamentoForm
from dotenv import load_dotenv
from django.shortcuts import render, redirect

load_dotenv(override=True)

GERENCIANET_PIX_KEY = os.getenv("GERENCIANET_PIX_KEY")


def processar_cobranca_pix(request):
    """
    Função principal que coordena todo o processo de criação de cobrança Pix.
    Chama as funções auxiliares para:
    - Processar o formulário.
    - Criar o payload da cobrança.
    - Enviar a requisição de criação de cobrança.
    - Obter os detalhes da cobrança (QR Code).

    Retorna uma resposta HTTP ou redirecionamento.
    """
    if request.method != 'POST':
        form = PagamentoForm()
        return render(request, 'pix/formulario_pagamento.html', {'form': form})

    form = PagamentoForm(request.POST)
    if not form.is_valid():
        return render(request, 'pix/formulario_pagamento.html', {'form': form})

    # Salvando o pagamento inicial
    pagamento = form.save()

    try:
        # Obter o access_token
        access_token = obter_access_token()

        # Criar e enviar a cobrança
        payload = criar_payload(pagamento)
        cobranca_data = enviar_requisicao_cobranca(payload, access_token)

        # Atualiza pagamento com dados de txid e id_loc
        pagamento.txid = cobranca_data.get('txid')
        pagamento.id_loc = cobranca_data.get('loc', {}).get('id')
        pagamento.save()

        # Obter detalhes da cobrança (QR Code)
        detalhes_data = obter_detalhes_cobranca(pagamento.id_loc, access_token)
        pagamento.qr_code = detalhes_data.get('qrCode')
        pagamento.link_visualizacao = detalhes_data.get('linkVisualizacao')
        pagamento.imagem_qrcode = detalhes_data.get('imagemQrcode')
        pagamento.status = "pendente"
        pagamento.save()

        # Redireciona para a página de sucesso
        return redirect('pix:sucesso', id_loc=pagamento.id_loc)

    except Exception as e:
        return render(request, 'pix/erro.html', {'erro': str(e)})


def obter_access_token():
    """
    Função que faz a requisição para o endpoint OAuth para obter o access_token.
    Retorna o access_token obtido da resposta.
    """
    url = "https://pix-h.api.efipay.com.br/oauth/token"

    # Recuperando as credenciais do arquivo .env
    # Defina CLIENT_ID no seu .env
    client_id = os.getenv("CLIENT_ID_HOMOLOGACAO")
    # Defina CLIENT_SECRET no seu .env
    client_secret = os.getenv("CLIENT_SECRET_HOMOLOGACAO")
    cert_file = os.getenv("CERT_FILE_HOMOLOGACAO")

    if not client_id or not client_secret:
        raise ValueError(
            "CLIENT_ID e CLIENT_SECRET devem estar definidos no arquivo .env.")

    # Dados necessários para a requisição OAuth
    data = {
        'grant_type': 'client_credentials',  # Tipo de grant
    }

    auth_value = f"{client_id}:{client_secret}"
    auth_base64 = base64.b64encode(auth_value.encode('utf-8')).decode('utf-8')

    headers = {
        'Content-Type': 'application/x-www-form-urlencoded',
        # Cabeçalho de Autenticação Basic
        'Authorization': f'Basic {auth_base64}'
    }

    try:
        # Fazendo a requisição POST para obter o token
        response = requests.post(
            url, data=data, headers=headers, cert=cert_file)
        response.raise_for_status()  # Levanta um erro se a requisição falhar

        # Extraindo o token da resposta JSON
        access_token = response.json().get('access_token')

        if not access_token:
            raise ValueError("Token de acesso não encontrado na resposta.")

        return access_token

    except requests.exceptions.RequestException as e:
        # Erro na requisição
        print(f"Erro ao fazer a requisição: {e}")
        raise


def formatar_valor(valor):
    """Formata o valor para garantir que tenha 2 casas decimais."""
    return "{:.2f}".format(valor)


def criar_payload(pagamento):
    """Cria o payload para a solicitação de cobrança."""
    valor_formatado = formatar_valor(pagamento.valor)
    return {
        "calendario": {"expiracao": 3600},
        "devedor": {"cpf": pagamento.cpf, "nome": pagamento.nome},
        "valor": {"original": str(valor_formatado)},
        "chave": GERENCIANET_PIX_KEY,
        "solicitacaoPagador": "Informe o número ou identificador do pedido."
    }


def enviar_requisicao_cobranca(payload, access_token):
    """Envia a solicitação de criação de cobrança e retorna a resposta."""
    url = "https://pix-h.api.efipay.com.br/v2/cob"
    headers = {'Authorization': f'Bearer {access_token}'}
    cert_file = os.getenv("CERT_FILE_HOMOLOGACAO")

    try:
        response = requests.post(
            url, json=payload, headers=headers, cert=cert_file, timeout=30)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        raise Exception(f"Erro na requisição de cobrança: {e}")


def obter_detalhes_cobranca(id_loc, access_token):
    """Obtém os detalhes da cobrança pelo id_loc."""
    detalhes_url = f"https://pix-h.api.efipay.com.br/v2/loc/{id_loc}/qrcode"
    headers = {'Authorization': f'Bearer {access_token}'}
    cert_file = os.getenv("CERT_FILE_HOMOLOGACAO")

    try:
        response = requests.get(
            detalhes_url, headers=headers, cert=cert_file, timeout=20)
        response.raise_for_status()

        return response.json()
    except requests.exceptions.RequestException as e:
        raise Exception(f"Erro ao obter detalhes da cobrança: {e}")


def processar_formulario(request):
    """Processa o formulário de pagamento e cria a cobrança Pix."""
    form = PagamentoForm(request.POST)
    if form.is_valid():
        pagamento = form.save()
        payload = criar_payload(pagamento)

        try:
            cobranca_data = enviar_requisicao_cobranca(payload)
            pagamento.txid = cobranca_data.get('txid')
            pagamento.id_loc = cobranca_data.get('loc', {}).get('id')
            pagamento.save()

            detalhes_data = obter_detalhes_cobranca(pagamento.id_loc)
            pagamento.qr_code = detalhes_data.get('qrcode')
            pagamento.link_visualizacao = detalhes_data.get('linkVisualizacao')
            pagamento.imagem_qrcode = detalhes_data.get('imagemQrcode')
            pagamento.status = "pendente"
            pagamento.save()

            return redirect('pix:sucesso', id_loc=pagamento.id_loc)
        except Exception as e:
            return render(request, 'pix/erro.html', {'erro': str(e)})

    return render(request, 'pix/formulario_pagamento.html', {'form': form})


def gerar_cobranca_pix(request):
    """Controlador principal para gerar cobrança Pix."""
    if request.method == 'POST':
        return processar_formulario(request)
    else:
        form = PagamentoForm()
        return render(request, 'pix/formulario_pagamento.html', {'form': form})


def sucesso(request, id_loc):
    try:
        # Tentando buscar o pagamento pelo id_loc (como CharField)
        # Usando loc_id para recuperar o pagamento
        pagamento = Pagamento.objects.get(id_loc=id_loc)
    except Pagamento.DoesNotExist:
        # Caso o pagamento não seja encontrado, exibe erro
        raise Http404("Pagamento não encontrado.")

    return render(request, 'pix/sucesso.html', {'pagamento': pagamento})

SIMPLES/pix/templates/pix/erro.html
<!-- templates/pix/erro.html -->

<h1>Erro ao criar pagamento!</h1>
<p>Ocorreu um erro ao tentar gerar o pagamento. Detalhes:</p>
<pre>{{ erro }}</pre>

SIMPLES/pix/templates/pix/formulario_pagamento.html
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <!-- Exibe os campos do formulário -->

  {% if form.errors %}
  <div class="errors">
    {% for field in form %} {% if field.errors %}
    <div class="error">
      <strong>{{ field.label }}:</strong>
      {% for error in field.errors %}
      <p>{{ error }}</p>
      {% endfor %}
    </div>
    {% endif %} {% endfor %}
  </div>
  {% endif %}

  <button type="submit">Submeter</button>
</form>

SIMPLES/pix/templates/pix/sucesso.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Pagamento Realizado com Sucesso</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
  <style>
    .container {
      max-width: 800px;
      margin-top: 50px;
    }

    .qr-code img {
      width: 200px;
      height: 200px;
    }

    .card {
      margin-top: 20px;
    }
  </style>
</head>

<body>
  <div class="container">
    <!-- Botão para abrir o modal -->
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#successModal">
      Ver Detalhes do Pagamento
    </button>

    <!-- Modal -->
    <div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="successModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="successModalLabel">
              Pagamento Gerado com Sucesso!
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p><strong>Nome:</strong> {{ pagamento.nome }}</p>
            <p><strong>Cpf:</strong> {{ pagamento.cpf }}</p>
            <p><strong>TXID:</strong> {{ pagamento.txid }}</p>
            <p><strong>Status:</strong> {{ pagamento.status }}</p>
            <p><strong>Valor:</strong> R$ {{ pagamento.valor }} </p>

            <div class="qr-code">
              <h4>QR Code para Pagamento:</h4>
              <img src="{{ pagamento.imagem_qrcode }}" alt="QR Code" />
            </div>

            <div class="mt-4">
              <a href="{{ pagamento.link_visualizacao }}" target="_blank" class="btn btn-primary">Ver Pagamento</a>
            </div>
            <div class="mt-4">
              <a class="btn btn-primary" onclick="copiarTexto('{{ pagamento.qr_code }}')">Pix copia e cola
              </a>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">
              Fechar
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="mt-4">
      <a href="{% url 'pix:gerar_pix' %}" class="btn btn-secondary">Voltar ao Formulário</a>
    </div>
  </div>
  </div>
  </div>

  <!-- Scripts -->
  <script>
    function copiarTexto(texto) {
      navigator.clipboard
        .writeText(texto)
        .then(() => {
          alert('Texto copiado com sucesso!');
        })
        .catch((err) => {
          alert('Falha ao copiar texto: ' + err);
        });
    }
  </script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>